### PR TITLE
feat(#466): add wallet GetVersion fixed method

### LINKED ISSUE #466: [FEATURE] Wallet: GetVersion

### PR DESCRIPTION
**Pull request by jakubmkowalski**
Closes #466
This pull request implements the `GetVersion` method for the `Wallet` type and adds corresponding tests to ensure correct validation of the `originator` parameter. The main focus is on returning the wallet version and validating input.

Implementation of `GetVersion`:

* [`pkg/wallet/wallet.go`](diffhunk://#diff-ea88400ee9978d3861f790f89a8efae2e437c92fa450cf110dbde7a2a0fcbc42L388-R395): Implements the `GetVersion` method to return a static version string and validate the `originator` parameter, returning an error if validation fails.

Testing and validation:

* [`pkg/wallet/wallet_get_version_test.go`](diffhunk://#diff-a4b5824d1233191612d2baf76490364ef98871eb17fbfdc2efc8ac9d0d4082eeR1-R44): Adds tests to verify that invalid `originator` values are correctly rejected by `GetVersion`, ensuring no side effects occur when validation fails.

### CODE REVIEW

File: pkg/wallet/wallet_get_version_test.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+import (
+	"strings"
+	"testing"
+
+	sdk "github.com/bsv-blockchain/go-sdk/wallet"
+	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/wallet/internal/testabilities"
+)
+
+func TestWalletGetVersionArgsValidation(t *testing.T) {
```
Comment (mgosek-4chain) [inline pkg/wallet/wallet_get_version_test.go:14]: Could you please explain why we don't need a test for happy path scenario? 🤔

File: pkg/wallet/wallet.go [hunk 2]
```diff
@@ -385,6 +385,12 @@ func (w *Wallet) GetNetwork(ctx context.Context, args any, originator string) (*
...
 // GetVersion retrieves the current version string of the wallet.
 func (w *Wallet) GetVersion(ctx context.Context, args any, originator string) (*sdk.GetVersionResult, error) {
-	// TODO implement me
-	panic("implement me")
+	if err := validate.Originator(originator); err != nil {
+		return nil, fmt.Errorf("invalid originator: %w", err)
+	}
+
+	return &sdk.GetVersionResult{
+		Version: "wallet-brc100-1.0.0",
```
Comment (chris-4chain) [inline pkg/wallet/wallet.go]: please make a special file and create a constant variable for this.
And I think, it's better to make it not v1 yet - as not all features are covered right now. So, I'm suggesting `"go-wallet-brc100-0.0.1"`

File: pkg/wallet/wallet.go [hunk 3]
```diff
@@ -385,6 +385,12 @@ func (w *Wallet) GetNetwork(ctx context.Context, args any, originator string) (*
 
 // GetVersion retrieves the current version string of the wallet.
 func (w *Wallet) GetVersion(ctx context.Context, args any, originator string) (*sdk.GetVersionResult, error) {
```
Comment (chris-4chain) [inline pkg/wallet/wallet.go]:
```suggestion
func (w *Wallet) GetVersion(_ context.Context, _ any, originator string) (*sdk.GetVersionResult, error) {
```

**Review by chris-4chain — CHANGES_REQUESTED** [review]

**Review by ac4ch — APPROVED** [review]

File: pkg/wallet/wallet_get_version_test.go (hunk 1 above)
Comment (jakubmkowalski) [reply pkg/wallet/wallet_get_version_test.go:14]: added

File: pkg/wallet/wallet.go (hunk 2 above)
Comment (jakubmkowalski) [reply pkg/wallet/wallet.go]: Version changed to yours suggestion, file with variable moved to the defs package

File: pkg/wallet/wallet.go (hunk 3 above)
Comment (jakubmkowalski) [reply pkg/wallet/wallet.go]: fixed

**Review by chris-4chain — APPROVED** [review]
