### PR TITLE
fix(#318): fix shallow copy issue across Resty http client instances.

### LINKED ISSUE #318: [BUG] Fix issue with cloning the HTTP client across services

### PR DESCRIPTION
**Pull request by mgosek-4chain**
## Linked Issues / Tickets

"Closes #318".

## Testing Procedure

Describe the tests you've added or any testing steps you've taken.

- [X] I have added new unit tests
- [X] All tests pass locally
- [X] I have tested manually in my local environment

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have run the linter

### CODE REVIEW

File: pkg/defs/services.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ const (
 	BHSTestURL = "http://localhost:8080"
 
 	// BHSApiKey is the token for the BHS service
-	BHSApiKey = ""
+	BHSApiKey = "token_abcd123456"
```
Comment (chris-4chain) [inline pkg/defs/services.go]: If it's your "custom" APIKey to BHS, I wouldn't put it here.
Or if it's a BHS default - in this case, it's ok.

**Review by ac4ch — APPROVED** [review]

**Review by chris-4chain — APPROVED** [review]
